### ISSUE TITLE
Query in loop

### ISSUE THREAD

**Issue by rmcgirr83** [dmzx/Groups-in-viewtopic#1]
You are running a query within a loop which is causing the query count to increase when viewing a topic and is not server friendly.

**Comment by dmzx** [comment]
Need to check on that!

**Comment by dmzx** [comment]
Rich do you have some sample code so I can take a look?

**Comment by rmcgirr83** [comment]
No but you should remove this https://github.com/dmzx/Groups-in-viewtopic/blob/master/event/listener.php#L68-L77 from that event.  That is what is causing the query in loop.  You could build an array first prior to that, using an event, and use it instead.

maybe using this event `core.viewtopic_before_f_read_check` build a cache and then use the cache output.  You could probably even pull all the groups a user is a member of by querying the user group table.

**Comment by rmcgirr83** [comment]
You know I don't mind helping you but it would be nice if you at least gave me some credit for the mods of mine you are converting into extensions.  For example, this one https://github.com/dmzx/Email-List the code in that controller file looks very, very familiar.

**Comment by dmzx** [comment]
Rich I did put you as Author to that extension see https://github.com/dmzx/Email-List/blob/master/composer.json#L18-L20 
Help is always welcome if you have time ;)

**Comment by rmcgirr83** [comment]
Ah, okay didn't see it in composer.
